panch_agema_admin:
    resource: "@PanchAgemaAdminBundle/Controller/"
    type:     annotation
    prefix:   /

panch_agema:
    resource: "@PanchAgemaBundle/Controller/"
    type:     annotation
    prefix:   /

fos_user:
    resource: "@FOSUserBundle/Resources/config/routing/all.xml"
